export const SET_ACTIVE_PLAYER = 'SET_ACTIVE_PLAYER'
export const ADVANCE_GAME_STATE = 'ADVANCE_GAME_STATE'
export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL'
export const TURN_OFF_MODALS = 'TURN_OFF_MODALS'
